# Generated by Django 6.0.2 on 2026-05-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('BODY', 'Body'), ('ANIMAL', 'Animal'), ('FAMILY', 'Family'), ('PLACE', 'Place'), ('NUMBER', 'Number'), ('COLOR', 'Color'), ('GREETING', 'Greeting'), ('VERB', 'Verb'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
