# Generated by Django 6.0.2 on 2026-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_word_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='arabic_word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
